<?php

use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class CrudTest extends TestCase
{

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testExample()
    {
        $content = nl2br(file_get_contents('app/Http/api_routes.php'));
        $content = str_replace("\r", "", $content);
        $content = str_replace("\n", "", $content);
        $this->assertEquals('<?php<br />',$content);

        $content = nl2br(file_get_contents('app/Http/custom_routes.php'));
        $content = str_replace("\r", "", $content);
        $content = str_replace("\n", "", $content);
        $this->assertEquals('<?php<br /><br />/* custom routes generated by CRUD */<br />',$content);
    }
}
